version: '3.8'

services:
  video-translation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-translation-api
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./test_data:/app/test_data:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    env_file:
      - .env
    restart: unless-stopped

